#!/bin/bash
# Eksekusi di node MOLLY
echo "molly" > /etc/hostname; hostname "molly"
cat > /etc/hosts << EOF
127.0.0.1   localhost
127.0.1.1   molly molly.k17.com
EOF
rm -f /etc/resolv.conf
cat > /etc/resolv.conf << EOF
nameserver 10.72.5.2
nameserver 10.72.5.3
nameserver 192.168.122.1
EOF
