#!/bin/bash
# Eksekusi di node EPSILON
echo "epsilon" > /etc/hostname; hostname "epsilon"
cat > /etc/hosts << EOF
127.0.0.1   localhost
127.0.1.1   epsilon epsilon.k17.com
EOF
rm -f /etc/resolv.conf
cat > /etc/resolv.conf << EOF
nameserver 10.72.5.2
nameserver 10.72.5.3
nameserver 192.168.122.1
EOF
